In [1]:
import pandas as pd
import numpy as np

In [38]:
df_price = pd.DataFrame({'month':['2018-01', '2018-02', '2018-03', '2018-04', '2018-05', '2018-06'], 'price': [0.3, 0.4, 0.2, 0.5, 0.7, 0.1]}, index=list(range(6)))
df_price

     month  price
0  2018-01    0.3
1  2018-02    0.4
2  2018-03    0.2
3  2018-04    0.5
4  2018-05    0.7
5  2018-06    0.1

In [41]:
df_word = pd.DataFrame({'word':['아파트', '서울', '매매', '상승', '하락'], 'percent': [0.4, 0.2, 0.1, 0.2, 0.1]}, index=list(range(5)))
df_word

  word  percent
0  아파트      0.4
1   서울      0.2
2   매매      0.1
3   상승      0.2
4   하락      0.1

In [59]:
df_word_test = pd.DataFrame({'word':None, 'word_test':None}, index=list(range(252)))
df_word_test.head()

   word word_test
0  None      None
1  None      None
2  None      None
3  None      None
4  None      None

In [51]:
df_word_test['word'] = df_word['word']
df_word_test

  word word_test
0  아파트      None
1   서울      None
2   매매      None
3   상승      None
4   하락      None

In [52]:
for i in range(len(df_word['percent'])):
  total = 0
  for j in range(len(df_price['price'])):
    total += (df_word.loc[i, 'percent'] * df_price.loc[j, 'price'])
    print(total)
  avg = total / len(df_price['price'])
  df_word_test.loc[i, 'word_test'] = avg
  print(f'avg: {avg}')

0.12
0.28
0.36000000000000004
0.56
0.8400000000000001
0.8800000000000001
avg: 0.1466666666666667
0.06
0.14
0.18000000000000002
0.28
0.42000000000000004
0.44000000000000006
avg: 0.07333333333333335
0.03
0.07
0.09000000000000001
0.14
0.21000000000000002
0.22000000000000003
avg: 0.036666666666666674
0.06
0.14
0.18000000000000002
0.28
0.42000000000000004
0.44000000000000006
avg: 0.07333333333333335
0.03
0.07
0.09000000000000001
0.14
0.21000000000000002
0.22000000000000003
avg: 0.036666666666666674

In [53]:
df_word_test

  word word_test
0  아파트  0.146667
1   서울  0.073333
2   매매  0.036667
3   상승  0.073333
4   하락  0.036667

In [54]:
df_word = pd.read_excel('/content/전체언론사 단어 빈도수 평균.xlsx', index_col = None)
df_word.head()

   Unnamed: 0 two_word     count
0           1       증여  0.001063
1           4       규제  0.006074
2           6       주택  0.006975
3           7       매매  0.019999
4           8      아파트  0.095531

In [55]:
df_word.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 252 entries, 0 to 251
Data columns (total 3 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Unnamed: 0  252 non-null    int64
 1   two_word    252 non-null    object
 2   count       252 non-null    float64
dtypes: float64(1), int64(1), object(1)
memory usage: 6.0+ KB

In [56]:
df_word.drop('Unnamed: 0', axis = 1, inplace = True)

In [57]:
df_word.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 252 entries, 0 to 251
Data columns (total 2 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   two_word  252 non-null    object
 1   count     252 non-null    float64
dtypes: float64(1), object(1)
memory usage: 4.1+ KB

In [58]:
df_word.head()

  two_word     count
0       증여  0.001063
1       규제  0.006074
2       주택  0.006975
3       매매  0.019999
4      아파트  0.095531

In [61]:
df_word_test['word'] = df_word['two_word']
df_word_test.head()

  word word_test
0   증여      None
1   규제      None
2   주택      None
3   매매      None
4  아파트      None

In [62]:
df_word_test.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 252 entries, 0 to 251
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   word       252 non-null    object
 1   word_test  0 non-null      object
dtypes: object(2)
memory usage: 5.9+ KB

In [66]:
df_price = pd.read_excel('/content/월간 아파트 지수 통계.xlsx', index_col = None)
df_price.head()

   Unnamed: 0      서울       변환값
0  2018-01-01  65.602  0.000000
1  2018-02-01  66.249  0.018467
2  2018-03-01  67.080  0.042185
3  2018-04-01  67.624  0.057712
4  2018-05-01  67.893  0.065390

In [67]:
df_price.drop(columns = 'Unnamed: 0', inplace = True)

In [68]:
df_price.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 60 entries, 0 to 59
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   서울      60 non-null     float64
 1   변환값     60 non-null     float64
dtypes: float64(2)
memory usage: 1.1 KB

In [69]:
for i in range(len(df_word['count'])):
  total = 0
  for j in range(len(df_price['변환값'])):
    total += (df_word.loc[i, 'count'] * df_price.loc[j, '변환값'])
    # print(total)
  avg = total / len(df_price['변환값'])
  df_word_test.loc[i, 'word_test'] = avg
  # print(f'avg: {avg}')

In [70]:
df_word_test.head()

  word word_test
0   증여  0.000539
1   규제  0.003081
2   주택  0.003538
3   매매  0.010144
4  아파트  0.048456

In [71]:
df_word_test.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 252 entries, 0 to 251
Data columns (total 2 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   word       252 non-null    object
 1   word_test  252 non-null    object
dtypes: object(2)
memory usage: 14.0+ KB

In [77]:
df_word_test = df_word_test.sort_values(by = 'word_test', ascending=False)

In [79]:
df_word_test.reset_index(drop = True, inplace = True)

In [80]:
df_word_test.head(30)

   word word_test
0   아파트  0.048456
1    서울  0.013018
2    매매  0.010144
3    하락  0.009222
4    거래  0.007832
5    상승  0.007015
6    만에  0.005794
7    강남  0.005094
8    집값  0.004751
9   부동산  0.004616
10   가격  0.003773
11   주택  0.003538
12   매수  0.003155
13   규제  0.003081
14   전세  0.003068
15   시장  0.002953
16   최고  0.002823
17  재건축  0.002789
18   전국  0.002726
19  수도권  0.002659
20   심리  0.002401
21   분양  0.002355
22   셋값   0.00225
23   평균  0.002064
24   승률  0.002056
25   역대  0.002051
26   대책  0.001952
27  상승세  0.001949
28   연속  0.001949
29   최저  0.001929

In [81]:
df_word_test.tail(30)

    word word_test
222   시티  0.000286
223   미분  0.000284
224   경신  0.000276
225   늘어  0.000276
226   모두  0.000273
227  래미안  0.000273
228   여파  0.000273
229   노원  0.000273
230  전문가  0.000273
231   불안  0.000271
232  힐스테  0.000271
233   기록  0.000268
234   김포  0.000268
235   사상  0.000268
236   여전  0.000266
237   거주  0.000263
238  늘었다  0.000263
239   건중  0.000263
240  뛰었다  0.000263
241   건설  0.000263
242   한강  0.000263
243   강화  0.000261
244   대형  0.000261
245   동반  0.000261
246   없는  0.000261
247  여전히  0.000261
248   중소  0.000258
249   조짐  0.000258
250  집주인  0.000258
251   입지  0.000255

In [82]:
df_word_test.to_excel('/content/단어 긍정 부정.xlsx', index = False)